var ram=['apple','banana','mango'];
console.log(ram.length);
var mohan=['mango','apple','banana'];
console.log(mohan.length);
var roy=['apple','mango','banana'];
console.log(roy.length);
var totalcount=ram.length+mohan.length+roy.length;
console.log(totalcount);
var finalarray=totalcount.length;
finalarray=[ram+" "+mohan+" "+roy];
console.log(finalarray);
